import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Cursor from "@/components/ui/Cursor";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "@/components/ui/Footer";
import GoogleAnalytics  from "@/components/GoogleAnalytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Just listen back to original music",
  description: "Generated by chatGPT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body className={`text-text bg-bg ${inter.className}`}>
        <Cursor className="" />
        {children}
        <ToastContainer toastStyle={{ backgroundColor: "#18316b" }} />
        <Footer />
        <GoogleAnalytics />
      </body>
    </html>
  );
}
